plt.figure(figsize=(6.5, 5.2))
plt.plot(E_det, W_det, lw=2.5, label="Deterministic skeleton")
plt.scatter([E_star], [W_star], s=70, label="Equilibrium")
plt.xlabel("Employment rate $E$")
plt.ylabel("Wage share $W$")
plt.title("Deterministic skeleton phase plot")
plt.legend()
plt.tight_layout()
plt.savefig("Fig_empirical_det_phase.png", dpi=300)
plt.show()
